services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      custom_bridge:
        ipv4_address: 192.168.100.10
    ports:
      - "8080:8080"

networks:
  custom_bridge:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.100.0/24